---
repos:
  - repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: remove-tabs

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: detect-private-key
      - id: check-ast
      - id: debug-statements

  - repo: git://github.com/pycqa/pydocstyle.git
    rev: 5.1.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        exclude: '^(docs|tasks|tests)|setup\.py'
        args: [--ignore-missing-imports]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://gitlab.com/PyCQA/flake8
    rev: '3.8.4'
    hooks:
      - id: flake8
        additional_dependencies: ['pep8-naming']
        # Ignore all format-related checks as Black takes care of those.
        args: ['--ignore', 'E2,W5', '--select', 'E,W,F,N', '--max-line-length=150']
